version: '3'
services:
  users-service:
    build: ./users-service
    ports:
      - "8000:80"
    depends_on:
      - messagebroker 
    volumes:
      - ./users-service:/var/www/html
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
  notifications-service:
    build: ./notifications-service
    ports:
      - "8001:80"
    depends_on:
      - messagebroker 
    volumes:
      - ./notifications-service:/var/www/html
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
  messagebroker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
