version: '3'
services:
  users-service:
    build: ./users-service
    ports:
      - "8000:80"
    depends_on:
      - messagebroker 
    volumes:
      - ./users-service:/var/www/html
  notifications-service:
    build: ./notifications-service
    ports:
      - "8001:80"
    depends_on:
      - messagebroker 
    volumes:
      - ./notifications-service:/var/www/html
  messagebroker:
    image: rabbitmq:3-management # Example using a RabbitMQ image
    ports:
      - "5672:5672" # RabbitMQ's default port 
      - "15672:15672" # Management interface