# Use the official PHP 8.3 image (Alpine) for a small image
FROM php:8.3-fpm-alpine

# Install system dependencies
RUN apk update && apk add --no-cache \
    sqlite-dev \
    linux-headers \
    && docker-php-ext-install pdo pdo_sqlite sockets \
    && rm -rf /var/cache/apk/*

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set the working directory
WORKDIR /var/www/html

# Copy the application code
COPY . .

# Create SQLite database file and give permissions
RUN touch database/database.sqlite \
    && chown -R www-data:www-data database

# Install dependencies
#RUN composer install --no-interaction --no-plugins --no-scripts --prefer-dist


