# Use the official PHP 8.3 image (Alpine) for a small image
FROM php:8.3-fpm-alpine

# Install system dependencies
RUN apk update && apk add --no-cache \
    linux-headers \
    && docker-php-ext-install sockets \
    && rm -rf /var/cache/apk/*

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set the working directory
WORKDIR /var/www/html

# Copy the application code
COPY . .

# Set permissions to allow Laravel to write to the storage folder
RUN chgrp -R www-data storage bootstrap/cache \
    && chmod -R ug+rwx storage bootstrap/cache

# Install dependencies
#RUN composer install --no-interaction --no-plugins --no-scripts --prefer-dist
